/* tslint:disable */
/* eslint-disable */
/**
 * Medication Management API
 * Medication management for the Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ladaivanna.matveeva@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface MedicationListEntry
 */
export interface MedicationListEntry {
    /**
     * Unique id of the entry in this medication list
     * @type {string}
     * @memberof MedicationListEntry
     */
    'id': string;
    /**
     * Name of medication in medication list
     * @type {string}
     * @memberof MedicationListEntry
     */
    'name': string;
    /**
     * Dosage of the medication per intake
     * @type {string}
     * @memberof MedicationListEntry
     */
    'dosage': string;
    /**
     * How many times the medication should be taken per day
     * @type {number}
     * @memberof MedicationListEntry
     */
    'frequencyPerDay': number;
    /**
     * Expiration date of the medication
     * @type {string}
     * @memberof MedicationListEntry
     */
    'expirationDate'?: string;
}

/**
 * MedicationListApi - axios parameter creator
 * @export
 */
export const MedicationListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * By using ambulanceId you get list of entries in ambulance medication list
         * @summary Provides the ambulance medication list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMedicationListEntries: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getMedicationListEntries', 'ambulanceId', ambulanceId)
            const localVarPath = `/medication/{ambulanceId}/entries`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MedicationListApi - functional programming interface
 * @export
 */
export const MedicationListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MedicationListApiAxiosParamCreator(configuration)
    return {
        /**
         * By using ambulanceId you get list of entries in ambulance medication list
         * @summary Provides the ambulance medication list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMedicationListEntries(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MedicationListEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMedicationListEntries(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MedicationListApi - factory interface
 * @export
 */
export const MedicationListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MedicationListApiFp(configuration)
    return {
        /**
         * By using ambulanceId you get list of entries in ambulance medication list
         * @summary Provides the ambulance medication list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMedicationListEntries(ambulanceId: string, options?: any): AxiosPromise<Array<MedicationListEntry>> {
            return localVarFp.getMedicationListEntries(ambulanceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MedicationListApi - interface
 * @export
 * @interface MedicationListApi
 */
export interface MedicationListApiInterface {
    /**
     * By using ambulanceId you get list of entries in ambulance medication list
     * @summary Provides the ambulance medication list
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicationListApiInterface
     */
    getMedicationListEntries(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<Array<MedicationListEntry>>;

}

/**
 * MedicationListApi - object-oriented interface
 * @export
 * @class MedicationListApi
 * @extends {BaseAPI}
 */
export class MedicationListApi extends BaseAPI implements MedicationListApiInterface {
    /**
     * By using ambulanceId you get list of entries in ambulance medication list
     * @summary Provides the ambulance medication list
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicationListApi
     */
    public getMedicationListEntries(ambulanceId: string, options?: AxiosRequestConfig) {
        return MedicationListApiFp(this.configuration).getMedicationListEntries(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }
}


