/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MatveevaMedicationList {
    }
}
declare global {
    interface HTMLMatveevaMedicationListElement extends Components.MatveevaMedicationList, HTMLStencilElement {
    }
    var HTMLMatveevaMedicationListElement: {
        prototype: HTMLMatveevaMedicationListElement;
        new (): HTMLMatveevaMedicationListElement;
    };
    interface HTMLElementTagNameMap {
        "matveeva-medication-list": HTMLMatveevaMedicationListElement;
    }
}
declare namespace LocalJSX {
    interface MatveevaMedicationList {
    }
    interface IntrinsicElements {
        "matveeva-medication-list": MatveevaMedicationList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "matveeva-medication-list": LocalJSX.MatveevaMedicationList & JSXBase.HTMLAttributes<HTMLMatveevaMedicationListElement>;
        }
    }
}
